---
- name: Playbook with pre/post tasks
  hosts: localhost
  gather_facts: false
  pre_tasks:
    - name: Pre task 1
      debug:
        msg: "Pre 1"
    - name: Pre task 2
      debug:
        msg: "Pre 2"
  roles:
    - test_role
  post_tasks:
    - name: Post task 1
      debug:
        msg: "Post 1"
  tasks:
    - name: Regular task
      debug:
        msg: "Regular"
